# Generated by Django 3.2.5 on 2021-07-07 17:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial_squashed_0003_remove_under_represented_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accessibility_needs',
            field=models.CharField(blank=True, max_length=1083, verbose_name='Do you have specific accessibility needs at the conference?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sponsoring_interest',
            field=models.CharField(choices=[('', '----'), ('Y', 'Yes, I can make an introduction'), ('N', 'No')], default='', max_length=1, verbose_name='Would your company be interested in sponsoring the event?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='under_represented_details',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Gender identity'), ('S', 'Sexual orientation'), ('R', 'Race or ethnicity'), ('A', 'Age'), ('E', 'Educational background'), ('C', 'Socioeconomic status or background'), ('D', 'Disability status'), ('O', 'I decline to answer'), ('X', 'Other (please specify)')], max_length=17, verbose_name='I identify as a member of the following underrepresented group(s):'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='under_represented_group',
            field=models.CharField(choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'Prefer not to say')], default='', max_length=1, verbose_name='Do you identify as a member of an under-represented group in computing?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='under_represented_other',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name=''),
        ),
    ]
