# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='under_represented_details',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'E', b'Ethnicity'), (b'A', b'Age'), (b'G', b'Gender'), (b'S', b'Sexual Orientation'), (b'D', b'Disability'), (b'O', b'Opt-out')], max_length=11, verbose_name=b'Check all that apply:'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='under_represented_population',
            field=models.CharField(choices=[(b'', b'----'), (b'Y', b'Yes'), (b'N', b'No'), (b'O', b'I would prefer not to answer')], default=b'', max_length=1, verbose_name=b'Do you feel that you or your talk represent a population under-represented in the Python and/or Data community?'),
        ),
    ]
