# Generated by Django 2.2.6 on 2019-10-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0003_standardize_markdown_links'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAdditionalSpeakerThrough',
            fields=[
            ],
            options={
                'constraints': [],
                'proxy': True,
                'indexes': [],
                'verbose_name': 'Additional Speaker',
            },
            bases=('symposion_proposals.additionalspeaker',),
        ),
    ]
