# Generated by Django 3.1.5 on 2021-01-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial_squashed_0003_remove_under_represented_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='audience_background',
            field=models.CharField(blank=True, max_length=400, verbose_name='Audience background needed to attend'),
        ),
    ]
