# Generated by Django 3.0.7 on 2020-06-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial_squashed_0003_remove_under_represented_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='already_recording',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is there a recording of this talk/tutorial already online?'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='proposal',
            name='recording_url',
            field=models.URLField(blank=True, default='', max_length=2083, verbose_name='If yes, what is the link?'),
        ),
    ]
