# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='under_represented_details',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('E', 'Ethnicity'), ('A', 'Age'), ('G', 'Gender'), ('S', 'Sexual Orientation'), ('D', 'Disability'), ('O', 'Opt-out')], max_length=11, verbose_name='Check all that apply:'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='under_represented_population',
            field=models.CharField(choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'I would prefer not to answer')], default='', max_length=1, verbose_name='Do you feel that you or your talk represent a population under-represented in the Python and/or Data community?'),
        ),
    ]
