# Generated by Django 2.2.10 on 2020-02-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial_squashed_0003_remove_under_represented_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
