# Generated by Django 2.2.4 on 2019-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("proposals", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="travel_stipend",
            field=models.BooleanField(
                default=False,
                help_text="To advance our goal of supporting diverse voices "
                "and enhancing the open source scientific computing community "
                "through inclusion, we have limited funds available "
                "for speaker stipends. If you would not otherwise "
                "be able to attend, please check this box for consideration "
                "for this funding in an amount not to exceed $500. "
                "Note that this has no bearing on your application, "
                "and your response will not be visible "
                "to the Proposal Selection Committee.",
                verbose_name="I would like to be considered for a stipend",
            ),
        )
    ]
