# Generated by Django 2.2.10 on 2020-02-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_make_affiliation_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='first_time_at_pydata',
            field=models.CharField(blank=True, choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'Prefer not to say')], default='', max_length=1, verbose_name='Is this your first time speaking at JupyterCon?'),
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='first_time_at_pydata',
            new_name='first_time_at_jupytercon',
        ),
    ]
