# Generated by Django 2.2.8 on 2020-01-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposaladditionalspeakerthrough'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='under_represented_details',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='under_represented_other',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='under_represented_population',
        ),
    ]
