# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_add_under_represented_population_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='under_represented_population',
            field=models.CharField(choices=[(b'', b'----'), (b'Y', b'Yes'), (b'N', b'No'), (b'O', b'I would prefer not to answer')], default=b'', max_length=1, verbose_name=b"Do you feel that you or your talk represent a population under-represented in the Python and/or Data community? In no way will this data be used as part of your proposal. This will only be used to gather diversity statistics in order to further NumFOCUS' mission."),
        ),
    ]
