# Generated by Django 3.1.5 on 2021-01-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposal_audience_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='outline',
            field=models.TextField(blank=True, verbose_name='Brief Bullet Point Outline'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='outline_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
