# Generated by Django 3.0.7 on 2020-07-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_add_recording_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='specialized_track',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Algorithmic Accountability'), (2, 'Causal and Statistical Methods'), (3, 'Data Science in Production'), (4, 'Data Visualization & Interpretability'), (5, 'Julia for Python Users & Julia Users'), (6, 'Lessons from Industry'), (7, 'Open Science')], default=0, verbose_name='Please choose a specialized track, if any'),
        ),
    ]
