# Generated by Django 2.2.10 on 2020-02-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_change_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accomodation_needs',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Do you have any accommodation needs at the conference? Examples include: sign language, closed captioning, mobility, mother's room, etc. "),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='What is your gender?  (Female, Male, Non-binary, Other)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='referral',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Where did you hear about this CFP?  Please include sharer (specific organization) and platform (Examples:  Blogpost, Twitter, LinkedIn, Slack, etc.)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='under_represented_group',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Do you identify as an under-represented group with respect to one or more of these: gender, age (40+), race, sexual orientation, or other self-reported category?'),
        ),
    ]
