# Generated by Django 3.0.7 on 2020-07-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_specialized_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='other_language',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Would this content be presented in a language other than English? If so, please indicate here.'),
        ),
    ]
