# Generated by Django 3.2.5 on 2021-07-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_replace_audience_level_with_prior_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='prior_knowledge_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='To attend the presentation, it would be recommended that the participant have some knowledge in:'),
        ),
    ]
