# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-25 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_add_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='affiliation',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='first_time_at_pydata',
            field=models.CharField(blank=True, choices=[(b'', b'----'), (b'Y', b'Yes'), (b'N', b'No'), (b'O', b'I would prefer not to answer')], default=b'', max_length=1, verbose_name=b'Is this your first time speaking at a PyData event?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='phone_number',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Phone number - to be used for last-minute schedule changes'),
        ),
    ]
