# Generated by Django 3.1.5 on 2021-01-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_outline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='first_time_at_pydata',
        ),
    ]
