# Generated by Django 3.2.5 on 2021-07-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_prior_knowledge_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='outline',
            field=models.TextField(blank=True, help_text="Brief outline. Will be made public if your proposal is accepted. Edit using <a href='https://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='Brief Bullet Point Outline'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='outline_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
