# Generated by Django 3.1.5 on 2021-01-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_remove_proposal_first_time_at_pydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='recording_online',
            field=models.BooleanField(default=False, verbose_name='Is there a recording of this talk/tutorial already online?'),
        ),
    ]
