# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_add_three_fields_to_cfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='under_represented_other',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='first_time_at_pydata',
            field=models.CharField(blank=True, choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'Prefer not to say')], default='', max_length=1, verbose_name='Is this your first time speaking at a PyData event?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='under_represented_details',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Gender identity'), ('E', 'Ethnicity, nationality, skin color, race'), ('S', 'Sexual orientation'), ('C', 'Socioeconomic status'), ('R', 'Religion'), ('A', 'Age'), ('D', 'Ability'), ('O', 'Do not wish to provide'), ('X', 'Other (please specify)')], max_length=17, verbose_name='Along which dimension(s) you self-identify as underrepresented? Check all that apply:'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='under_represented_population',
            field=models.CharField(choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'Prefer not to say')], default='', max_length=1, verbose_name='Do you self-identify as an underrepresented minority in either the PyData/NumFOCUS community or in your professional field?'),
        ),
    ]
