# Generated by Django 3.0.7 on 2020-07-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_other_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='first_time_at_pydata',
            field=models.CharField(blank=True, choices=[('', '----'), ('N', 'No'), ('1', 'Yes - First-time technical speaker (any)'), ('2', 'Yes - First-time speaker (PyData) with 3+ conference talks'), ('3', 'Yes - First-time speaker (PyData) with < 3 conference talks')], default='', max_length=1, verbose_name='Is this your first time speaking at a PyData event?'),
        ),
    ]
