# Generated by Django 2.2.10 on 2020-03-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_add_additional_proposal_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='format',
            field=models.TextField(blank=True, help_text='Please describe what portion of your tutorial you plan to spend on student exercises, lecture, or other activities.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Please provide details of the level of programming and other topic-specific experience this tutorial is aiming for. Who is this tutorial the most beneficial for?', verbose_name='Target Audience'),
        ),
    ]
