# Generated by Django 3.2.5 on 2021-07-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposal_outline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='recording_online',
            field=models.BooleanField(default=False, verbose_name='Is there a recording of this talk/tutorial already online?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='recording_url',
            field=models.URLField(blank=True, max_length=2083, verbose_name='If yes, what is the link?'),
        ),
    ]
