# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-06 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_update_under_represented_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'Created'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=b'Last Modified'),
        ),
    ]
