# Generated by Django 2.2.10 on 2020-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_add_format_and_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='requests',
            field=models.TextField(blank=True, default='', help_text='Let us know if you have specific needs or special requests — for example, requests that involve accessibility, audio, or restrictions on when your proposal can be scheduled. We will be providing appropriate seating for attendees, a projector, and a microphone for you.', verbose_name='Requests'),
        ),
    ]
