# Generated by Django 3.1.5 on 2021-01-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposal_recording_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='affiliation',
            field=models.CharField(max_length=200, verbose_name='Affiliation (Company, School, Independent)'),
        ),
    ]
