# Generated by Django 3.1.5 on 2021-01-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_alter_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accessibility_needs',
            field=models.CharField(blank=True, help_text='Examples include, but not limited to: sign language, closed captioning, assistance with recording, etc. Please indicate the specific need so we can plan in advance.', max_length=1083, verbose_name='Do you have specific accessibility needs at the conference?'),
        ),
    ]
