# Generated by Django 3.2.5 on 2021-07-08 02:10

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proposals', '0006_proposal_recording_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='TrackTaggedProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_tracktaggedproposal_tagged_items', to='contenttypes.contenttype', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_tracktaggedproposal_items', to='proposals.proposaltrack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='tracks',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='track_tagged_proposals', through='proposals.TrackTaggedProposal', to='proposals.ProposalTrack', verbose_name='Tracks'),
        ),
    ]
