# Generated by Django 3.0.7 on 2020-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_change_affilation_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='commitment',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='We are asking all speakers to commit to presenting at PyData Global 2020 if their proposals are accepted. This commitment will greatly simplify the Program Committee’s deliberations and will enable us to communicate acceptances and bring together the conference program much more quickly. If accepted, can you commit to presenting at PyData Global 2020?'),
            preserve_default=False,
        ),
    ]
