# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-16 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_add_urlfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='code_url',
            field=models.URLField(blank=True, default='', help_text="Location of this proposal's code repository (e.g. Github).", max_length=2083, verbose_name='Repository'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='slides_url',
            field=models.URLField(blank=True, default='', help_text='Location of slides for this proposal (e.g. SlideShare, Google Drive).', max_length=2083, verbose_name='Slides'),
        ),
    ]
