# Generated by Django 3.0.7 on 2020-07-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposal_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='mentoring',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('T', 'Yes, providing technical mentorship'), ('C', 'Yes, providing communication mentorship'), ('B', 'Yes, both technical and communication mentoring')], default="N", max_length=1, verbose_name='Would you be interested in mentoring other speakers?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='mentorship',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Would you like to be considered for our speaker mentorship program?'),
            preserve_default=False,
        ),
    ]
