# Generated by Django 3.2.5 on 2021-07-08 03:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposal_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='official_keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='official_tagged_proposals', through='proposals.TaggedProposal', to='proposals.ProposalKeyword', verbose_name='Keywords'),
        ),
    ]
