# Generated by Django 2.2.10 on 2020-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_make_affiliation_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='accomodation_needs',
            field=models.CharField(blank=True, default='', help_text='Examples include, but not limited to: sign language, closed captioning, mobility, parent room, diet, etc. Please indicate the specific need so we can plan in advance.', max_length=200, verbose_name='Do you have specific\u200b accessibility needs at the conference\u200b?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='affiliation',
            field=models.CharField(help_text='For the purpose of this talk.', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='first_time_at_jupytercon',
            field=models.CharField(blank=True, choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'Prefer not to say')], default='', max_length=1, verbose_name='Is this your first time presenting at JupyterCon?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='What is your gender?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='referral',
            field=models.CharField(blank=True, default='', help_text='Please include the source (e.g. organization, individual) and the channel/platform (e.g. Twitter, LinkedIn, Slack, email, blog post, etc.).', max_length=200, verbose_name='Where did you hear about this CFP?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='under_represented_group',
            field=models.CharField(blank=True, default='', help_text='If so, please list.', max_length=200, verbose_name='Do you identify as an under-represented group with respect to one or more of these: gender, age (40+), race, sexual orientation, or other self-reported category?'),
        ),
    ]
