# Generated by Django 3.1.5 on 2021-01-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposal_accessibility_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='recording_release',
        ),
    ]
