# Generated by Django 3.1.5 on 2021-01-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_remove_proposal_recording_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='under_represented_group',
            field=models.CharField(choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'Prefer not to say')], default='', max_length=1, verbose_name='Do you identify as a member of an under-represented group?'),
        ),
    ]
