# Generated by Django 2.2.10 on 2020-03-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_proposal_field_verbose_and_help_text_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='format',
            new_name='tutorial_format',
        ),
    ]
