# Generated by Django 3.2.5 on 2021-07-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_alter_proposal_official_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='country',
            field=models.CharField(default='', max_length=200, verbose_name='What is your country of residence?'),
            preserve_default=False,
        ),
    ]
