# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_update_under_represented_population_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='affiliation',
            field=models.CharField(max_length=200),
        ),
    ]
