# Generated by Django 3.2.5 on 2021-07-08 04:00

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_proposal_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default=None, help_text='Please mention in the additional notes if you will have multiple speakers presenting from different timezones', verbose_name='What is your local timezone?'),
            preserve_default=False,
        ),
    ]
