# Generated by Django 2.2.10 on 2020-03-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_rename_proposal_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='gdpr_data_exemption',
            field=models.BooleanField(default=False, verbose_name='If I chose to provide NumFOCUS with data about my ethnic origin, data concerning my health or data concerning my sexual orientation I hereby exempt them from the prohibition in Art. 9(1) GDPR to process such personal data until I withdraw this permission.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gdpr_grant',
            field=models.BooleanField(default=False, verbose_name='I hereby grant NumFOCUS [P.O. Box 90596, Austin, TX 78709, USA] the right to use this information for the purpose of organizing the event JupyterCon according to GDPR.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gdpr_revoke_awareness',
            field=models.BooleanField(default=False, verbose_name='I am aware that I can revoke this permission at any time according to Art. 7(1) GDPR. This withdrawal of consent can be sent to [NumFOCUS, P.O. Box 90596, Austin, TX 78709, USA, privacy@numfocus.org, +1 \u200b(512) 831-2870]. The withdrawal of consent shall not affect the lawfulness of processing based on consent before its withdrawal however.'),
        ),
    ]
