# Generated by Django 3.1.5 on 2021-01-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_proposal_under_represented_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='sponsoring_interest',
            field=models.CharField(choices=[('', '----'), ('Y', 'Yes, I can make an introduction'), ('N', 'No')], default='', max_length=1, verbose_name='Would your company be interested in sponsoring the event?'),
        ),
    ]
