# Generated by Django 2.2.10 on 2020-03-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_add_gdpr_checkboxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='under_represented_group',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1, verbose_name='Do you identify as an under-represented group with respect to one or more of these: gender, age (40+), race, sexual orientation, or other self-reported category?'),
        ),
    ]
