# Generated by Django 3.2.5 on 2021-07-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_proposal_mentorship_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='first_time_at_pydata',
            field=models.CharField(blank=True, choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'Prefer not to say')], default='', max_length=1, verbose_name='Are you a first-time speaker?'),
        ),
    ]
