# Generated by Django 3.2.5 on 2021-07-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_proposal_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='content_language',
            field=models.CharField(blank=True, max_length=200, verbose_name='Would this content be presented in a language other than English? If so, please indicate here.'),
        ),
    ]
