# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proposals', '0011_add_proposal_keyword_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorTaggedProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_editortaggedproposal_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_editortaggedproposal_items', to='proposals.ProposalKeyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='editor_keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='', through='proposals.EditorTaggedProposal', to='proposals.ProposalKeyword', verbose_name='Editor Keywords'),
        ),
    ]
