# Generated by Django 3.2.5 on 2021-07-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_proposal_content_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='mentoring',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Would you be interested in mentoring other speakers?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='mentorship',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Would you like to be considered for our speaker mentorship program?'),
        ),
    ]
