# Generated by Django 3.2.6 on 2021-08-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_alter_proposal_first_time_at_pydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='affiliation',
            field=models.CharField(choices=[('C', 'Company'), ('S', 'School'), ('I', 'Independent')], max_length=1),
        ),
    ]
