# Generated by Django 3.0.7 on 2020-06-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_virtual_cfp_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='under_represented_group',
            field=models.CharField(blank=True, choices=[('', '----'), ('Y', 'Yes'), ('N', 'No'), ('O', 'Prefer not to say')], default='', max_length=1, verbose_name='Do you identify as an under-represented group with respect to one or more of these: gender, age (40+), race, sexual orientation, or other self-reported category?'),
        ),
    ]
