# Generated by Django 3.2.6 on 2021-08-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_alter_proposal_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='travel_at_own_expense',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Are you able to travel to Eindhoven at your own expense?'),
        ),
    ]
