# Generated by Django 3.0.8 on 2020-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_proposal_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Novice'), (3, 'Intermediate'), (2, 'Experienced')], default=3),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='av_equipment_needed',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes, audio'), (2, 'Yes, video'), (3, 'Yes, both')], default=0, verbose_name='Do you need audio and/or video recording equipment?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='mentorship',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Would you like to be considered for our speaker mentorship program?'),
        ),
    ]
