# Generated by Django 3.2.5 on 2021-07-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_alter_proposal_first_time_at_pydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='stipend',
            field=models.BooleanField(default=False, help_text='We have a number of modest speaker stipends available based on need; the quantity available will depend on successful sponsorship of this effort. <strong>If a stipend would make a difference in your ability to prepare and present your material<strong>, please check this box for consideration for this funding. Proposal selection is need-blind; asking to be considered for need-based stipends will have no bearing on the consideration or likelihood of acceptance of your proposal.', verbose_name='I would like to be considered for a stipend'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='stipend_amount',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='If yes, please provide an estimated amount for the stipend.'),
        ),
    ]
