# Generated by Django 3.0.8 on 2020-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_add_defaults_for_posters'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='attendance',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Who else (if anyone) from the project is likely to attend?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='issue_curation',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Will you be able to curate issues for first-time attendees to work on ahead of the sprint?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='merge_ability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Will you be able to merge PRs in real-time during the sprint?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='num_attendees',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Approximately how many attendees would be ideal for you to accommodate in the sprint?'),
        ),
    ]
