# Generated by Django 3.2.7 on 2021-10-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_proposal_travel_at_own_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='affiliation',
            field=models.CharField(max_length=200, verbose_name='Affilation (Company, School, Independent)'),
        ),
    ]
