# Generated by Django 3.2.7 on 2021-10-06 00:09

from django.db import migrations


def migrate_affiliations(apps, schema_editor):
    Proposal = apps.get_model("proposals", "Proposal")
    for proposal in Proposal.objects.iterator():
        if proposal.affiliation == "C":
            proposal.affiliation = "Company"
            proposal.save()
        elif proposal.affiliation == "S":
            proposal.affiliation = "Schoool"
            proposal.save()
        elif proposal.affiliation == "I":
            proposal.affiliation = "Independent"
            proposal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_alter_proposal_affiliation'),
    ]

    operations = [
        migrations.RunPython(migrate_affiliations),
    ]
