# Generated by Django 3.0.8 on 2020-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_add_default_to_commitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='affiliation',
            field=models.CharField(max_length=200, verbose_name='Affiliation (Company, School, Independent)'),
        ),
    ]
