# Generated by Django 3.0.8 on 2020-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_change_affiliation_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='stipend',
            field=models.BooleanField(default=False, help_text='We have a number of modest speaker stipends available based on need; the quantity available will depend on successful sponsorship of this effort. <strong>If a stipend would make a difference in your ability to prepare and record your material, and participate in live Q&A</strong>, please check this box for consideration for this funding. Proposal selection is need-blind; asking to be considered for need-based stipends will have no bearing on the consideration or likelihood of acceptance of your proposal.', verbose_name='I would like to be considered for a stipend'),
        ),
    ]
