# Generated by Django 3.0.8 on 2020-07-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_alter_stipend_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='review_ready',
            field=models.BooleanField(default=False, help_text='Check the box below to indicate to the program committee your proposal is ready for review. This proposal will not be considered until the box is marked.', verbose_name='This proposal is ready for review'),
        ),
    ]
