# Generated by Django 2.2.9 on 2020-01-19 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('reviews', '0001_initial'), ('reviews', '0002_proposalfeedback_proposalresult'), ('reviews', '0003_proposalfeedback_proposal'), ('reviews', '0004_proposalnotification')]

    dependencies = [
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True, choices=[(3, '+1 — Good proposal and I will argue for it to be accepted.'), (1, '+0 — OK proposal, but I will not argue for it to be accepted.'), (-1, '−0 — Weak proposal, but I will not argue against acceptance.'), (-3, '−1 — Serious issues and I will argue to reject this proposal.')])),
                ('comment', models.TextField(blank=True)),
                ('comment_html', models.TextField(blank=True, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to='proposals.Proposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'Undecided'), ('A', 'Accepted'), ('R', 'Rejected'), ('S', 'Standby')], default='U', max_length=1)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_result', to='proposals.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('comment_html', models.TextField(blank=True, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_feedback', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_feedback', to='proposals.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('body', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Date this notification was created and sent')),
                ('proposals', models.ManyToManyField(blank=True, related_name='review_notifications', to='proposals.Proposal')),
            ],
        ),
    ]
