# Generated by Django 2.0.13 on 2019-04-12 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True, choices=[(3, '+1 — Good proposal and I will argue for it to be accepted.'), (1, '+0 — OK proposal, but I will not argue for it to be accepted.'), (-1, '−0 — Weak proposal, but I will not argue against acceptance.'), (-3, '−1 — Serious issues and I will argue to reject this proposal.')])),
                ('comment', models.TextField(blank=True)),
                ('comment_html', models.TextField(blank=True, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to='proposals.Proposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
