# Generated by Django 3.0.5 on 2020-05-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial_squashed_0004_proposalnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalvote',
            name='score',
            field=models.SmallIntegerField(blank=True, choices=[(3, '+1 — Good proposal and I will argue for it to be accepted.'), (1, '+0 — OK proposal, but I will not argue for it to be accepted.'), (0, '±0 — I abstain from voting on this proposal.'), (-1, '−0 — Weak proposal, but I will not argue against acceptance.'), (-3, '−1 — Serious issues and I will argue to reject this proposal.')]),
        ),
    ]
