# Generated by Django 2.0.13 on 2019-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
        ('reviews', '0003_proposalfeedback_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('body', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Date this notification was created and sent')),
                ('proposals', models.ManyToManyField(blank=True, related_name='review_notifications', to='proposals.Proposal')),
            ],
        ),
    ]
