# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0003_make_sessionrole_submitted_timezone_aware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='day',
        ),
        migrations.RemoveField(
            model_name='session',
            name='slots',
        ),
        migrations.AlterUniqueTogether(
            name='sessionrole',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sessionrole',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessionrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='SessionRole',
        ),
    ]
