# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0004_remove_session_and_sessionrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='name',
        ),
    ]
