# Generated by Django 3.0.10 on 2020-09-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("symposion_schedule", "0004_add_slot_datetimes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slot",
            options={
                "ordering": ["day", "start_dt", "end_dt"],
                "verbose_name": "slot",
                "verbose_name_plural": "slots",
            },
        ),
        migrations.RemoveField(
            model_name="slot",
            name="end",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="start",
        ),
    ]
