# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0005_remove_slot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='content_override_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
