# Generated by Django 3.0.10 on 2020-09-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0005_remove_slot_time_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['day', 'start', 'end'], 'verbose_name': 'slot', 'verbose_name_plural': 'slots'},
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='end_dt',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='start_dt',
            new_name='start',
        ),
    ]
