# Generated by Django 2.2.9 on 2020-01-19 05:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    replaces = [('cms', '0001_initial'), ('cms', '0002_modify_mailchimp_field'), ('cms', '0003_lengthen_url_fields'), ('cms', '0004_homepage_ticketing_section'), ('cms', '0005_add_homepage_footer_fields'), ('cms', '0006_add_help_text_to_image_fields'), ('cms', '0007_homepage_news_keynote_section'), ('cms', '0008_remove_homepage_mailchimp_list_id'), ('cms', '0009_homepage_footer1_section'), ('cms', '0010_homepage_streamfields_are_not_required'), ('cms', '0011_add_image_credit_fields'), ('cms', '0012_venuepage_streamfields_are_not_required')]

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('conference_info_section', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True)),
                ('pydata_info_section', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True)),
                ('ticketing_url', models.URLField(blank=True, max_length=2083)),
                ('background_image', models.ForeignKey(blank=True, help_text='Maximum file size is 10 MB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('logo_image', models.ForeignKey(blank=True, help_text='Maximum file size is 10 MB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('ticketing_section', wagtail.core.fields.RichTextField(default='<h2>Tickets</h2>')),
                ('footer_email', models.EmailField(blank=True, default='admin@pydata.org', max_length=254)),
                ('footer_twitter', models.CharField(blank=True, default='PyData', max_length=15)),
                ('news_keynote_section', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True)),
                ('footer1_section', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True, help_text="Displays on left side of the site's footer section. Will display mini code of conduct by default.")),
                ('image_credit', wagtail.core.fields.RichTextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VenuePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('venue_info_section', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True, help_text="Information about the conference's venue.")),
                ('google_maps_url', models.URLField(blank=True, max_length=2083)),
                ('hotel_info_section', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True, help_text="Information about the conference's hotel(s).")),
                ('background_image', models.ForeignKey(blank=True, help_text='Maximum file size is 10 MB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('image_credit', wagtail.core.fields.RichTextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
