# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_modify_mailchimp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='ticketing_url',
            field=models.URLField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='venuepage',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=2083),
        ),
    ]
