# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_homepage_ticketing_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_email',
            field=models.EmailField(blank=True, default='admin@pydata.org', max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_twitter',
            field=models.CharField(blank=True, default='PyData', max_length=15),
        ),
    ]
