# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 21:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_add_help_text_to_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_keynote_section',
            field=wagtail.wagtailcore.fields.StreamField([('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock())]),
        ),
    ]
