# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-18 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_homepage_news_keynote_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='mailchimp_list_id',
        ),
    ]
