# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-29 21:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_remove_homepage_mailchimp_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer1_section',
            field=wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], default=None, help_text="Displays on left side of the site's footer section. Will display mini code of conduct by default."),
        ),
    ]
