# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 05:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_homepage_footer1_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='conference_info_section',
            field=wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer1_section',
            field=wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True, help_text="Displays on left side of the site's footer section. Will display mini code of conduct by default."),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news_keynote_section',
            field=wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='pydata_info_section',
            field=wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
    ]
