# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 20:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_add_image_credit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuepage',
            name='hotel_info_section',
            field=wagtail.wagtailcore.fields.StreamField([('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock())], blank=True, help_text="Information about the conference's hotel(s)."),
        ),
        migrations.AlterField(
            model_name='venuepage',
            name='venue_info_section',
            field=wagtail.wagtailcore.fields.StreamField([('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock())], blank=True, help_text="Information about the conference's venue."),
        ),
    ]
