dependencies:
  - {role: common}
galaxy_info:
  author: Martey Dodoo
  description: Ansible role for PostgreSQL databases.
  company: NumFOCUS
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
