dependencies:
  - {role: common}
galaxy_info:
  author: Martey Dodoo
  description: Ansible role for web servers.
  company: NumFOCUS
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
