- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true

- name: restart supervisor
  ansible.builtin.service:
    name: supervisor
    state: restarted
  become: true
