# Generated by Django 3.0.10 on 2020-09-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='timezone',
        ),
    ]
