# Generated by Django 2.0.13 on 2019-02-17 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='As you would like it to appear in the conference program.', max_length=100, verbose_name='Name')),
                ('biography', models.TextField(blank=True, help_text="A little bit about you.  Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>.", verbose_name='Biography')),
                ('biography_html', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, help_text='Maximum file size: 10 MB', upload_to='speaker_photos', verbose_name='Photo')),
                ('twitter_username', models.CharField(blank=True, help_text='Your Twitter account', max_length=15)),
                ('annotation', models.TextField(blank=True, verbose_name='Annotation')),
                ('invite_email', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Invite_email')),
                ('invite_token', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Invite token')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Speaker',
                'ordering': ['name'],
                'verbose_name_plural': 'Speakers',
            },
        ),
    ]
