# Generated by Django 2.2.2 on 2019-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=models.TextField(blank=True, help_text="A little bit about you.  Edit using <a href='https://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='Biography'),
        ),
    ]
