# Generated by Django 2.2.9 on 2020-01-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0004_make_speaker_slugs_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='github_username',
            field=models.CharField(blank=True, help_text='Your Github account', max_length=39),
        ),
    ]
