# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-25 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0004_make_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
    ]
