# Generated by Django 3.0.7 on 2020-06-23 21:18

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0005_speaker_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='speaker_timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, verbose_name='Timezone'),
        ),
    ]
