# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-21 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0005_fix_migrations_accidentally_rolling_back_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, help_text='Maximum file size: 10 MB', upload_to='speaker_photos', verbose_name='Photo'),
        ),
    ]
