# Generated by Django 3.0.8 on 2020-07-08 18:42

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0005_speaker_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='speaker_timezone',
            field=timezone_field.fields.TimeZoneField(default=None, verbose_name='Timezone'),
            preserve_default=False,
        ),
    ]
