# Generated by Django 3.2.5 on 2021-07-07 19:54

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0005_speaker_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default=None, verbose_name='Timezone'),
            preserve_default=False,
        ),
    ]
