# Generated by Django 3.2.5 on 2021-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0005_speaker_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=2083, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='personal_url',
            field=models.URLField(blank=True, max_length=2083, verbose_name='Personal Site URL'),
        ),
    ]
