# Generated by Django 3.0.7 on 2020-06-24 00:18

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0006_speaker_speaker_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speaker_timezone',
            field=timezone_field.fields.TimeZoneField(verbose_name='Timezone'),
        ),
    ]
