# Generated by Django 3.1.5 on 2021-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0006_speaker_speaker_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='personal_site_url',
            field=models.URLField(blank=True, max_length=2083, verbose_name='Personal site URL'),
        ),
    ]
