# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_link', models.URLField(default='https://pydata.org/become-a-sponsor.html', max_length=2083, verbose_name='Link to information about becoming a sponsor.')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'sponsor settings',
            },
        ),
    ]
