# Generated by Django 2.2.9 on 2020-01-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipsettings',
            name='info_link',
            field=models.URLField(default='https://pydata.org/pdf/sponsor-prospectus.pdf', max_length=2083, verbose_name='Link to sponsor prospectus.'),
        ),
    ]
