# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='abstract',
            field=models.TextField(help_text="Detailed outline. Will be made public if your proposal is accepted. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='additional_notes',
            field=models.TextField(blank=True, help_text="Anything else you'd like the program committee to know when making their selection: your past experience, etc. This is not made public. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='description',
            field=models.TextField(help_text='If your proposal is accepted this will be made public and printed in the program. Should be one paragraph, maximum 400 characters.', max_length=400, verbose_name='Brief Summary'),
        ),
    ]
