# Generated by Django 2.2.2 on 2019-06-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='abstract_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='additional_notes_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
