# Generated by Django 2.2.2 on 2019-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0002_make_presentation_html_uneditable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='abstract',
            field=models.TextField(help_text="Detailed outline. Will be made public if your proposal is accepted. Edit using <a href='https://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='additional_notes',
            field=models.TextField(blank=True, help_text="Anything else you'd like the program committee to know when making their selection: your past experience, etc. This is not made public. Edit using <a href='https://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='Additional Notes'),
        ),
    ]
