# Generated by Django 2.2.10 on 2020-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0003_standardize_markdown_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='abstract',
            field=models.TextField(help_text='This is a self-contained statement that summarizes the objective of the proposal, its outline, central thesis, and key takeaways. After reading the description, the audience should have an idea of the overall presentation and know what to expect. The description should also make clear what background knowledge is expected from the attendees. Include links to relevant source code, articles, videos, or other information that add context to your proposal.', verbose_name='Outline'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='If you have given a talk or poster before, feel free to include links to slides or videos.', verbose_name='Past experience and any other information you would like the reviewers to know.'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='description',
            field=models.TextField(help_text='Short, maximum 400 words. If your proposal is accepted this will be public and printed in the program. Should be one paragraph.', max_length=400, verbose_name='Brief summary'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='title',
            field=models.CharField(help_text='A clear title should convey in a few words what your talk is about.', max_length=100, verbose_name='Title'),
        ),
    ]
