# Generated by Django 3.0.10 on 2020-12-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0004_add_order_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsection',
            name='closed',
            field=models.BooleanField(null=True, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='proposalsection',
            name='published',
            field=models.BooleanField(null=True, verbose_name='Published'),
        ),
    ]
