# Generated by Django 2.2.10 on 2020-03-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0004_proposal_field_verbose_and_help_text_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='abstract',
            field=models.TextField(help_text='This is a self-contained statement that summarizes the objective of the proposal, its outline, central thesis, and key takeaways. After reading the description, the audience should have an idea of the overall presentation and what they will learn. The description should also make clear what background knowledge is expected from the attendees. Include links to relevant source code, articles, videos, or other information that add context to your proposal.', verbose_name='Outline'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='description',
            field=models.TextField(help_text='Short paragraph, maximum 400 characters. If your proposal is accepted, this will be in the public printed program.', max_length=400, verbose_name='Brief summary'),
        ),
    ]
