# Generated by Django 3.0.7 on 2020-06-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0005_auto_change_abstract_and_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='description',
            field=models.TextField(help_text='Short paragraph, maximum 400 characters. If your proposal is accepted, this will be in the public program.', max_length=400, verbose_name='Brief summary'),
        ),
    ]
