- name: Install certbot
  ansible.builtin.apt:
    name: certbot
    state: present
  become: true
  when: ssl_enabled

- name: Create .well-known directory
  ansible.builtin.file:
    mode: 0755
    path: "{{ project_root }}/.well-known"
    state: directory
  become: true
  when: ssl_enabled

# We use the "standalone" method because nginx needs a certificate to run,
# so the webroot method will not work when we provision the certificate for
# the first time.
- name: Run certbot and generate certificate
  ansible.builtin.command: >
    certbot certonly -n --standalone --agree-tos
    -d {{ website_domain }}
    -m {{ admin_email }}
    -w {{ project_root }}/.well-known
    --pre-hook "service nginx stop" --post-hook "service nginx start"
  args:
    creates: /etc/letsencrypt/live/{{ website_domain }}/fullchain.pem
  become: true
  when: ssl_enabled and environment_type != "development"
