- name: install certbot
  apt: name=certbot
       state=present
  become: true
  when: not cloudflare_enabled

- name: create .well-known directory
  file: path={{ project_root }}/.well-known
        state=directory
  become: true
  when: not cloudflare_enabled

# We use the "standalone" method because nginx needs a certificate to run,
# so the webroot method will not work when we provision the certificate for
# the first time.
- name: run certbot and generate certificate
  command: >
    certbot certonly -n --standalone --agree-tos
    -d {{ website_domain }}
    -m {{ admin_email }}
    -w {{ project_root }}/.well-known
    --pre-hook "service nginx stop" --post-hook "service nginx start"
  args:
    creates: /etc/letsencrypt/live/{{ website_domain }}/fullchain.pem
  become: true
  when: not cloudflare_enabled and environment_type != "development"
