- name: add nginx package key
  ansible.builtin.apt_key:
    id: 7BD9BF62
    state: present
    url: http://nginx.org/keys/nginx_signing.key
  become: true

- name: add mainline nginx repository
  ansible.builtin.apt_repository:
    repo: "deb http://nginx.org/packages/mainline/debian/ {{ ansible_lsb.codename }} nginx"
    state: present
  become: true

- name: update package list to get latest nginx
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: install nginx
  ansible.builtin.apt:
    pkg: nginx
    state: present
  become: true
  notify: restart nginx

- name: remove default nginx global configuration file
  ansible.builtin.file:
    path: "/etc/nginx/nginx.conf"
    state: absent
  become: true
  notify: restart nginx

- name: add customized nginx global configuration file
  ansible.builtin.template:
    dest: "/etc/nginx/nginx.conf"
    force: true
    group: root
    mode: 0644
    owner: root
    src: nginx-global.conf
  become: true
  notify: restart nginx

- name: remove default nginx site configuration file
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  become: true

- name: add customized http nginx site configuration file
  ansible.builtin.template:
    dest: "/etc/nginx/conf.d/{{ website_domain }}.conf"
    group: root
    mode: 0644
    owner: root
    src: nginx-site-http.conf
  become: true
  notify: restart nginx
  when: not ssl_enabled or environment_type == "development"

- name: add customized https nginx site configuration file
  ansible.builtin.template:
    dest: "/etc/nginx/conf.d/{{ website_domain }}.conf"
    group: root
    mode: 0644
    owner: root
    src: nginx-site-https.conf
  become: true
  notify: restart nginx
  when: ssl_enabled and environment_type != "development"

- name: remove default nginx ssl site configuration file
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/example-ssl.conf"
    state: absent
  become: true
  notify: restart nginx

- name: add custom logrotate configuration for nginx
  ansible.builtin.template:
    dest: "/etc/logrotate.d/nginx"
    group: root
    mode: 0644
    owner: root
    src: logrotate-nginx.conf
  become: true
