- name: add nginx package key
  apt_key: id=7BD9BF62 url=http://nginx.org/keys/nginx_signing.key state=present
  become: true

- name: add mainline nginx repository
  apt_repository: repo="deb http://nginx.org/packages/mainline/debian/ {{ ansible_lsb.codename }} nginx" state=present
  become: true

- name: update package list to get latest nginx
  apt: update_cache=yes
  become: true

- name: install nginx
  apt:  pkg=nginx state=present
  become: true
  notify: restart nginx

- name: remove default nginx global configuration file
  file:
    path: "/etc/nginx/nginx.conf"
    state: absent
  become: true
  notify: restart nginx

- name: add customized nginx global configuration file
  template: src=nginx-global.conf dest=/etc/nginx/nginx.conf
            force=yes
            owner=root group=root mode=0644
  become: true
  notify: restart nginx

- name: remove default nginx site configuration file
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  become: true

- name: add customized http nginx site configuration file
  template: src=nginx-site-http.conf
            dest=/etc/nginx/conf.d/{{ website_domain }}.conf
            owner=root group=root mode=0644
  become: true
  notify: restart nginx
  when: not ssl_enabled or environment_type == "development"

- name: add customized https nginx site configuration file
  template: src=nginx-site-https.conf
            dest=/etc/nginx/conf.d/{{ website_domain }}.conf
            owner=root group=root mode=0644
  become: true
  notify: restart nginx
  when: ssl_enabled and environment_type != "development"

- name: remove default nginx ssl site configuration file
  file:
    path: "/etc/nginx/conf.d/example-ssl.conf"
    state: absent
  become: true
  notify: restart nginx

- name: add custom logrotate configuration for nginx
  template: src=logrotate-nginx.conf dest=/etc/logrotate.d/nginx
            owner=root group=root mode=0644
  become: true
