- name: create pretalx configuration directory if necessary
  ansible.builtin.file:
    mode: 0755
    owner: "{{ ansible_user_id }}"
    path: "/etc/pretalx"
    state: "directory"
  become: true

- name: add custom pretalx configuration file
  ansible.builtin.template:
    dest: "/etc/pretalx/pretalx.cfg"
    mode: 0644
    owner: "{{ ansible_user_id }}"
    src: "pretalx.cfg.j2"
  notify: restart gunicorn

- name: add custom pretalx template
  ansible.builtin.template:
    dest: "{{ project_root }}/pretalx/data/templates/common/base.html"
    mode: 0400
    owner: "{{ ansible_user_id }}"
    src: "pretalx/common/base.html"

- name: database migrate
  ansible.builtin.command:
    cmd: "{{ virtualenv_root }}/current/bin/python -m pretalx migrate"
  notify: restart gunicorn

- name: collect static files
  ansible.builtin.command:
    cmd: "{{ virtualenv_root }}/current/bin/python -m pretalx rebuild"
  notify: restart nginx

- name: add pretalx cron job
  ansible.builtin.cron:
    job: "{{ virtualenv_root }}/current/bin/python -m pretalx runperiodic"
    name: "pretalx runperiodic"
    minute: "*/5"
    state: present
