- name: Restart redis
  ansible.builtin.service:
    name: redis-server
    state: restarted
  become: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Delete other virtualenvs
  ansible.builtin.shell: find  -maxdepth 1
         ! -path '.'
         ! -path './'$(basename $(readlink current))
         ! -path './'$(basename $(readlink previous))
         -type d -exec rm -rf {} +
  args:
    chdir: "{{ virtualenv_root }}"

- name: Restart gunicorn
  community.general.supervisorctl:
    name: gunicorn
    state: restarted
  become: true

- name: Mark fixtures as applied
  ansible.builtin.file:
    path: "{{ project_root }}/fixtures/.applied"
    state: touch
    mode: 0600
  tags:
    - fixtures

- name: Import sentry tasks
  ansible.builtin.import_tasks: sentry.yml
