- name: restart redis
  service: name=redis-server state=restarted
  become: true

- name: restart nginx
  service: name=nginx state=restarted
  become: true

- name: delete other virtualenvs
  shell: find  -maxdepth 1
         ! -path '.'
         ! -path './'$(basename $(readlink current))
         ! -path './'$(basename $(readlink previous))
         -type d -exec rm -rf {} +
  args:
    chdir: "{{ virtualenv_root }}"

- name: restart gunicorn
  supervisorctl: name=gunicorn state=restarted
  become: true

- name: mark fixtures as applied
  file:
    path: "{{ project_root }}/fixtures/.applied"
    state: touch
    mode: 0600
  tags:
    - fixtures

- include: sentry.yml
