name: Validate documentation
on:
  push:
    paths:
      - ".github/**"
      - "docs/**"
      - "requirements/development.txt"
jobs:
  rst-lint:
    name: Lint ReStructuredText documentation
    runs-on: ubuntu-latest
    container: python:3.9-bullseye
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Virtualenv caching
        uses: actions/cache@v3.3.2
        with:
          path: ~/venv/current
          key: ${{ runner.os }}-python3.9-venv-v1-${{ hashFiles('**/requirements/development.txt') }}-${{ hashFiles('**/requirements/production.txt') }}
          restore-keys: |
            ${{ runner.os }}-python3.9-venv-v1-${{ hashFiles('**/requirements/development.txt') }}-${{ hashFiles('**/requirements/production.txt') }}
            ${{ runner.os }}-python3.9-venv-v1-${{ hashFiles('**/requirements/development.txt') }}-
            ${{ runner.os }}-python3.9-venv-v1-
      - name: Install Python dependencies
        uses: mobolic/install-python-dependencies@v0.3.0
        with:
          virtualenv-location: "~/venv/current"
      - name: Run rstcheck
        run: ~/venv/current/bin/rstcheck --report-level warning docs/source/*.rst
