name: Validate documentation
on:
  push:
    paths:
      - ".github/**"
      - "docs/**"
      - "requirements/development.txt"
jobs:
  rst-lint:
    name: Lint ReStructuredText documentation
    runs-on: ubuntu-latest
    container: python:3.7-buster
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Virtualenv caching
        uses: actions/cache@v2
        with:
          path: ~/venv
          key: ${{ runner.os }}-python3.7-venv-v1-${{ hashFiles('**/requirements/development.txt') }}-${{ hashFiles('**/requirements/production.txt') }}
          restore-keys: |
            ${{ runner.os }}-python3.7-venv-v1-${{ hashFiles('**/requirements/development.txt') }}-${{ hashFiles('**/requirements/production.txt') }}
            ${{ runner.os }}-python3.7-venv-v1-${{ hashFiles('**/requirements/development.txt') }}-
            ${{ runner.os }}-python3.7-venv-v1-
      - name: Install libimagequant-dev
        uses: ./.github/actions/install-libimagequant-dev
      - name: Install Python dependencies
        uses: mobolic/install-python-dependencies@v0.1.0
      - name: Run rstcheck
        run: ~/venv/bin/rstcheck --report warning docs/source/*.rst
